### ISSUE TITLE
Can not read .ndpi file format.

### ISSUE THREAD

**Issue by ujjwalbaid0408** [cgohlke/tifffile#110]
Hi,

I am trying to ready .ndpi file format but stuck at the following error.
Any suggestion?

>>> t = tiffile.imread('OS1.ndpi')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ujjwa\anaconda3\lib\site-packages\tiffile\tifffile.py", line 567, in imread
    return tif.asarray(**kwargs)
  File "C:\Users\ujjwa\anaconda3\lib\site-packages\tiffile\tifffile.py", line 2023, in asarray
    result = pages[0].asarray(out=out, validate=validate,
  File "C:\Users\ujjwa\anaconda3\lib\site-packages\tiffile\tifffile.py", line 3779, in asarray
    strip = decompress(strip)
  File "C:\Users\ujjwa\anaconda3\lib\site-packages\tiffile\tifffile.py", line 3676, in decompress
    return imagecodecs.jpeg_decode(data, bitspersample, table,
  File "C:\Users\ujjwa\anaconda3\lib\site-packages\imagecodecs\imagecodecs.py", line 962, in jpeg_decode
    data = header + data + b'\xff\xd9'
TypeError: can only concatenate str (not "bytes") to str

**Comment by cgohlke** [comment]
What are the versions of tifffile and imagecodecs? Probably tifffile is outdated or there is a mismatch of tifffile and imagecodecs.

**Comment by ujjwalbaid0408** [comment]
Hi @cgohlke,

Thank you for pointing this out. I was using the older version "tiffile". I installed "tifffile" now and it is working.
