### ISSUE TITLE
How to opt in to strict tiff parsing?

### ISSUE THREAD

**Issue by jmuhlich** [cgohlke/tifffile#216]
Upon encountering certain kinds of corrupt data in tiff files, tifffile prints warnings via the logging module but tries to carry on as best it can. I sometimes prefer a hard failure so I can report this up to my own software's human user; they can then investigate what's wrong with their file. One case that just came up was a file that got truncated, where tifffile emitted messages like:
```
<tifffile.TiffPage 0 @16> <tifffile.TiffTag 270 @124> invalid value offset ...
<tifffile.TiffFile ...> generic series failed with TiffFileError: corrupted tag list at offset ...
<tifffile.TiffPages @16> invalid page offset ...
```
And no exception was raised but the resulting `TiffFile` had fewer pages than expected and the ImageDescription tag was missing (since it had been located near the end of the file and lost in the truncation). My code was very confused at this point.

It seems like calling code could replace `log_warning` with a new function that raises an exception, but this doesn't seem ideal. Do you have any thoughts on how to enable a "strict mode"? I suppose it may be tricky and even context-dependent to decide exactly what should be a hard error and what should continue to pass with a warning.

**Comment by cgohlke** [comment]
Thanks for raising the issue.

First, logging seems to work in this case. It gives relevant information what is wrong with the file and helps understand why the returned image is not as expected.

> tifffile prints warnings via the logging module but tries to carry on as best it can.

That is by design. Tifffile was basically invented to access data and metadata in non-compliant and corrupted TIFF files where libtiff fails.

Like other design decisions in tifffile, the "undefined behavior" in case of unsupported or corrupted files may not be adequate for many of today's use cases.

> I suppose it may be tricky and even context-dependent to decide exactly what should be a hard error and what should continue to pass with a warning.

Indeed. There are also cases where tifffile/imagecodecs raise exceptions and users asked for ways to ignore them.

> Do you have any thoughts on how to enable a "strict mode"? 

There is currently no option to specify a "strict mode". I'll look into that and see if it is feasible. Probably this should go along with using more logging levels. Testing will be tedious.

One wart of tifffile relevant to this issue is the series interface. There is currently no interface to read a specific type of series, e.g., OME or ImageJ, without falling back to other series types.

For now, try to verify certain aspects of your specific files before reading the image data. For example, verify the file contains certain number of pages or valid metadata.

**Comment by cgohlke** [comment]
How about a `loglevel` parameter that limits the maximum severity of errors being logged instead of raised? For example, the following code would raise an exception for files with ERROR level corruptions while logging WARNING and lower level errors:

```python
im = imread('corrupted.tif', loglevel=LOGLEVEL.WARNING)
```

Still, there are effectively only two logging levels and errors might be context-dependent as mentioned...

**Comment by cgohlke** [comment]
The `loglevel` approach turned out not too useful. Instead, how about making it easier to filter warnings using Python's stdlib. For example, the following filter should raise an error when an ERROR-level message is logged (like a corrupted tag or page). Not sure how pythonic that is and it's relying on undocumented internals...

```Python
import logging
import tifffile


def filter(record):
    # if record.funcName == 'fromfile':
    # if 'invalid value offset' in record.msg:
    if record.levelno == logging.ERROR:
        raise ValueError(record.msg)
    return True


tifffile.logger().addFilter(filter)
try:
    tifffile.imread(r'corrupted.tif')
except ValueError:
    ...
tifffile.logger().removeFilter(filter)
```

**Comment by joshmoore** [comment]
I'll add from the peanut gallery, filters based on the module can be activated longer-term (as opposed to per call since they should "do what you want") and/or activated for the whole interpreter using the `action:message:category:module:lineno` pattern:

```
$ PYTHONPATH=.. python t.py
/private/tmp/ttest/lib.py:4: UserWarning: foo
  warnings.warn("foo")

$ PYTHONPATH=.. python -W error:::ttest.lib t.py
Traceback (most recent call last):
  File "t.py", line 3, in <module>
    t.run()
  File "/private/tmp/ttest/lib.py", line 4, in run
    warnings.warn("foo")
UserWarning: foo
```

**Comment by cgohlke** [comment]
> python -W error:::ttest.lib t.py

That's a nice feature for warnings but does not work with logging. My understanding is that Python [warnings](https://docs.python.org/3/library/warnings.html) are directed at developers to fix something (e.g. the use of a deprecated function), while [logging](https://docs.python.org/3/library/logging.html) is to inform users about non-fatal, non-fixable runtime events (e.g., a minor corruption in a file).

**Comment by joshmoore** [comment]
🤦🏽 That's what happens when the peanut gallery tries to be helpful while working on a train. :smile: Really quite too bad that there's not a logging control like the [warning control](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS)!
