### ISSUE TITLE
Tiffpage.decode got problem for GeoTiff with JPEG7 compress

### ISSUE THREAD

**Issue by HowcanoeWang** [cgohlke/tifffile#229]
To reproduce:

create and activate environment

```bash
(base) ~ % conda create -n tifffilexport python=3.11
(base) ~ % conda activate tifffilexport
(tifffilexport) ~ % pip install tifffile imagecodecs
(tifffilexport) ~ % python
(tifffilexport) ~ % pip list
Package     Version
----------- ---------
imagecodecs 2023.9.18
numpy       1.26.0
pip         23.2.1
setuptools  68.0.0
tifffile    2023.9.26
wheel       0.41.2
```

To reproduce the error:

```python
>>> import tifffile as tf
>>> jpeg7dom = '...test_jpeg7_compress.tif' # the path for the geotiff file
>>> tif = tf.TiffFile(jpeg7dom)
>>> page = tif.pages[0]
>>> page.compression
<COMPRESSION.JPEG: 7>

# data prepare for page.decode()
>>> index = 10 # or any other index -> the row number of pixel matrix
>>> fh = page.parent.filehandle
>>> offset = page.dataoffsets[index]
>>> bytecount = page.databytecounts[index]
>>> fh.seek(offset)
>>> data = fh.read(bytecount)

# the error
>>> tile, indices, shape = page.decode(data, index)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hwang/anaconda/miniconda3/envs/tifffilexport/lib/python3.11/site-packages/tifffile/tifffile.py", line 8577, in decode_jpeg
    data_array: NDArray[Any] = imagecodecs.jpeg_decode(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hwang/anaconda/miniconda3/envs/tifffilexport/lib/python3.11/site-packages/imagecodecs/imagecodecs.py", line 1721, in jpeg_decode
    raise exc
  File "/Users/hwang/anaconda/miniconda3/envs/tifffilexport/lib/python3.11/site-packages/imagecodecs/imagecodecs.py", line 1696, in jpeg_decode
    return imagecodecs.jpeg8_decode(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "imagecodecs/_jpeg8.pyx", line 370, in imagecodecs._jpeg8.jpeg8_decode
imagecodecs._jpeg8.Jpeg8Error: Quantization table 0x00 was not defined
```

Some header and tables information:

```python
>>> page.jpegheader is None
True
>>> page.jpegtables
b'\xff\xd8\xff\xdb\x00C\x00\x03\x02\x02\x03\x02\x02\x03\x03\x03\x03\x04\x03\x03\x04\x05\x08\x05\x05\x04\x04\x05\n\x07\x07\x06\x08\x0c\n\x0c\x0c\x0b\n\x0b\x0b\r\x0e\x12\x10\r\x0e\x11\x0e\x0b\x0b\x10\x16\x10\x11\x13\x14\x15\x15\x15\x0c\x0f\x17\x18\x16\x14\x18\x12\x14\x15\x14\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\x97\x98\x99\x9a\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xff\xd9'
```

Personally guess it may caused by mixing the JPEG6 with JPEG7 compression format:

https://stackoverflow.com/questions/5733867/jpeg-from-tiff-jpeg-compressed

Or it may also caused by the software that I used to produce that geotiff. Here is the download link for downloading that geotiff for testing: https://drive.google.com/file/d/13U3XnNEqoc2Dd2w1lORhlsID2gGGURJd/view?usp=sharing

**Comment by cgohlke** [comment]
Pass the `jpegtables` to the decode function:
```python
tile, indices, shape = page.decode(data, index, jpegtables=page.jpegtables)
```
Works for me.
