### ISSUE TITLE
IndexError: list index out of range in _attribute

### ISSUE THREAD

**Issue by FiReTiTi** [cgohlke/tifffile#232]
Hi,
I use tifffile to convert images stored in a directory into an ome.tiff file. It works well most of the time, but sometimes I get the following error trace:

    Traceback (most recent call last):
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/Mcv/Images/ImageIO.py", line 209, in ImagesToOMETIF
    tif.write(stack[:, ::mag, ::mag], subfiletype=1,
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 2106, in write
    self._omexml.addimage(
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 15789, in addimage
    attributes = OmeXml._attributes(
                 ^^^^^^^^^^^^^^^^^^^
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 16007, in _attributes
    return ''.join(a for a in attributes if a)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 16007, in <genexpr>
    return ''.join(a for a in attributes if a)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 16005, in <genexpr>
    OmeXml._attribute(metadata, name, index_) for name in names
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 15981, in _attribute
    value = value[index]
            ~~~~~^^^^^^^
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/Mcv/Images/ImageIO.py", line 179, in ImagesToOMETIF
    with TiffWriter(ResultFullPath+ext, ome=True, bigtiff=isBigtiff) as tif:
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 3973, in __exit__
    self.close()
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 3537, in close
    self._write_image_description()
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 3734, in _write_image_description
    self._omexml.addimage(
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 15789, in addimage
    attributes = OmeXml._attributes(
                 ^^^^^^^^^^^^^^^^^^^
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 16007, in _attributes
    return ''.join(a for a in attributes if a)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 16007, in <genexpr>
    return ''.join(a for a in attributes if a)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 16005, in <genexpr>
    OmeXml._attribute(metadata, name, index_) for name in names
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/t/Python/miniconda3/envs/CF/lib/python3.11/site-packages/tifffile/tifffile.py", line 15981, in _attribute
    value = value[index]
            ~~~~~^^^^^^^
    IndexError: list index out of range


As I said, most of the time it works just fine and I can open the images using QuPath or Napari to double check. However, sometimes I get the previous error trace (always the exact same one), but I cannot link it to a number of images or dimensions.

All the images I try to convert are large tiff file (each dimension being between 30K to 60K) encoded in 16 bits, and I can have between 6 to 30ish of them, so the result image is big.

I use python 3.11.3, on Mac OS X and Centos, and the last version of tifffile.

Here is the code I use:

    def ImagesToOMETIF(DirPath: str, ResultFullPath: str,):

        imNames = imTools.ListImages(DirPath)
        Biomarkers = []
        ...
        isBigtiff = imTools.areBig(DirPath) # Check is the result will be big
        ext = ".ome.btf" if isBigtiff else ".ome.tif" # adapt the extension accordingly
        SubResolutions = max(1, imTools.PyramidLevel(stack)) # Find the number of decompositions in the pyramid

        resunit = 'MICROMETER'
        PixelBase = 1.

        extrameta = imTools.tryLoadMetadata(DirPath) # My own extra metadata

        with TiffWriter(ResultFullPath+ext, ome=True, bigtiff=isBigtiff) as tif:
            options = dict(dtype=stack.dtype, photometric='minisblack', tile=(512, 512), resolutionunit=resunit)

            metadata = {
                        'axes': 'CYX',
                        'Channel': {'Name': Biomarkers},
                        'ExtraMetaData': extrameta,
                        'PhysicalSizeX': PixelSize,
                        'PhysicalSizeXUnit': PixelUnit,
                        'PhysicalSizeY': PixelSize,
                        'PhysicalSizeYUnit': PixelUnit,
                        'Plane': {'PositionX': [0.0] * 16, 'PositionXUnit': [PixelUnit] * 16},
                        'SignificantBits': 16
                        }
            PixelSize = 1

            tif.write(stack, subifds=SubResolutions, resolution=(PixelBase / PixelSize, PixelBase / PixelSize), metadata=metadata, **options)

            for level in range(SubResolutions):
                mag = 2 ** (level + 1)
                tif.write(stack[:, ::mag, ::mag], subfiletype=1, resolution=(PixelBase / mag / PixelSize, PixelBase / mag / PixelSize), **options)

            tif.write((stack[0, ::8, ::8] >> 2), metadata={'Name': 'thumbnail'})


According to the trace, the issue seems to be happening when writing the sub-levels of the pyramid. When the error happens, it occurs immediately when trying to write the first level of magnification.

**Comment by cgohlke** [comment]
> `Biomarkers = []`
> `'Channel': {'Name': Biomarkers},`
> `'Plane': {'PositionX': [0.0] * 16, 'PositionXUnit': [PixelUnit] * 16},`

Make sure the array sizes for the channel names and plane metadata match the actual number of channels and planes.

**Comment by FiReTiTi** [comment]
Indeed, this is it.
Thank you very much for the help.

**Comment by FiReTiTi** [comment]
Thanks
