### ISSUE TITLE
`ndarray.newbyteorder` is no longer available in NumPy 2.0

### ISSUE THREAD

**Issue by lagru** [cgohlke/tifffile#238]
While preparing scikit-image for NumPy 2.0 in https://github.com/scikit-image/scikit-image/pull/7288, I encountered a test that fails because `tifffile` uses the `ndarray.newbyteorder` attribute that is no longer present in NumPy 2.0. To reproduce, download the following dataset from skimage https://gitlab.com/scikit-image/data/-/blob/master/lily-of-the-valley-fluorescence.tif, and run

```python
import tifffile
tifffile.imread("/path/to/lily-of-the-valley-fluorescence.tif")
```
which shows the following traceback

<details><summary>Details</summary>
<p>

```
Traceback (most recent call last):
  File "/home/lg/.local/lib/micromamba/envs/skimagedev312/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-cb273d77b0e0>", line 1, in <module>
    tifffile.imread("/home/lg/Tmp/lily-of-the-valley-fluorescence.tif")
  File "/home/lg/.local/lib/micromamba/envs/skimagedev312/lib/python3.12/site-packages/tifffile/tifffile.py", line 1106, in imread
    return tif.asarray(
           ^^^^^^^^^^^^
  File "/home/lg/.local/lib/micromamba/envs/skimagedev312/lib/python3.12/site-packages/tifffile/tifffile.py", line 4336, in asarray
    result = self.filehandle.read_array(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lg/.local/lib/micromamba/envs/skimagedev312/lib/python3.12/site-packages/tifffile/tifffile.py", line 14568, in read_array
    result = result.newbyteorder()
             ^^^^^^^^^^^^^^^^^^^
AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.
```

</p>
</details> 

I wouldn't call this a bug yet, but its something that seems like it can already be changed in preparation and seems to still be present on `main`:

https://github.com/cgohlke/tifffile/blob/5ced58caa74936ecc53f58ade94938e251e83138/tifffile/tifffile.py#L14568

NumPy version: 2.0.0.dev0+git20240109.6e3b923
tifffile version: 2023.12.9

**Comment by cgohlke** [comment]
Thanks for the heads-up. This will have to wait until at least a release candidate of numpy 2 is available.

**Comment by lagru** [comment]
You are welcome and noted. :blush:

**Comment by Slava-On** [comment]
I am getting the same error with Flux1.dev GGUF model, that is loaded in ComfyUI by unet loader node:

got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
!!! Exception during processing !!! `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.
Traceback (most recent call last):
  File "E:\Projects\ComfyUI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\ComfyUI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Projects\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 177, in load_unet
    sd = gguf_sd_loader(unet_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 30, in gguf_sd_loader
    reader = gguf.GGUFReader(path)
             ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\miniconda3\envs\comfyenv\Lib\site-packages\gguf\gguf_reader.py", line 94, in __init__
    if self._get(offs, np.uint32, override_order = '<')[0] != GGUF_MAGIC:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\miniconda3\envs\comfyenv\Lib\site-packages\gguf\gguf_reader.py", line 151, in _get
    .newbyteorder(override_order or self.byte_order)
     ^^^^^^^^^^^^
AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

Prompt executed in 0.09 seconds

**Comment by cgohlke** [comment]
> File "E:\Projects\miniconda3\envs\comfyenv\Lib\site-packages\gguf\gguf_reader.py", line 151, in _get
.newbyteorder(override_order or self.byte_order)

Wrong package. Report to `gguf`.

**Comment by Slava-On** [comment]
It worked earlier and was broken, when I installed xLabs IP adapter. Now, even workflows that worked before, would throw this loader error 😥

**Comment by cgohlke** [comment]
This is the wrong repository to report the issue.
