### ISSUE TITLE
Writing compressed 16-bit images fails in version 2020.8.25

### ISSUE THREAD

**Issue by John-Hennig** [cgohlke/tifffile#24]
The following code reads a 1024×1024 NumPy array of unsigned 16-bit integers from a file (example attached) and saves it as a TIFF image using zlib compression.

```python
from numpy import load
from tifffile import imwrite

image = load('image.npy')
imwrite('image.tif', image, compress=6)
```

This works as expected with TiffFile up until version `2020.8.13`. As of version `2020.8.25`, released a week ago, it fails with the following error trace-back:
```console
$ python test_imwrite.py
Traceback (most recent call last):
  File "test_imwrite.py", line 5, in <module>
    imwrite('image.tif', image, compress=6)
  File "C:\programs\Python\lib\site-packages\tifffile\tifffile.py", line 785, in imwrite
    return tif.save(data, shape, dtype, **kwargs)
  File "C:\programs\Python\lib\site-packages\tifffile\tifffile.py", line 2151, in save
    strip = compress(strip)
  File "C:\programs\Python\lib\site-packages\tifffile\tifffile.py", line 2015, in compress
    return compressor(data, level)
  File "C:\programs\Python\lib\site-packages\tifffile\tifffile.py", line 12176, in zlib_encode
    return zlib.compress(data, level)
ValueError: ndarray is not C-contiguous
```

The error occurs regardless of compression level (6 in the above code). It does not occur if `compress` is not specified, i.e. saving uncompressed images still works.

[image.npy.zip](https://github.com/cgohlke/tifffile/files/5163269/image.npy.zip)

**Comment by cgohlke** [comment]
Thank you! 
Fixed in tifffile v2020.9.3.
The issue was that F-contiguous arrays were no longer converted to C-order.
