### ISSUE TITLE
Limitations of Python 2.7 version

### ISSUE THREAD

**Issue by rk-exxec** [cgohlke/tifffile#250]
Can the Python 2.7 version of tifffile store ome metadata?
Or do I have to fall back to write json in the description?
I have to use Python 2.7 because Gwyddion does not support 3 yet.

```py
gwy_meta = container['/{0}/meta'.format(data_field_idx)]
meta_dict = {k:gwy_meta.get_value_by_name(k) for k in gwy_meta.keys_by_name()}

np_data = gwyutils.data_field_data_as_array(data_field)
metadata=dict(microscope="Olympus LEXT 4000", PhysicalSizeX=size[0]*1e6, PhysicalSizeY=size[1]*1e6, PhysicalSizeUnit="um", PhysicalSizeZ=0.8, **meta_dict)
tifffile.imwrite(str(new_filename.with_suffix(".ome.tif")), np_data, metadata=metadata)
```

I also cant use the resolution keyword, as I get this error:
```
Traceback (most recent call last):
  File "c:\Users\krr38985\Documents\Python\ridge_evaluation\gwypy_lext_processing.py", line 147, in <module>
    resolution=(1/dx, 1/dy))
  File "C:\Python27\lib\site-packages\tifffile\tifffile.py", line 783, in imwrite
    return tif.save(data, shape, dtype, **kwargs)
  File "C:\Python27\lib\site-packages\tifffile\tifffile.py", line 1665, in save
    addtag('XResolution', '2I', 1, rational(resolution[0]))
  File "C:\Python27\lib\site-packages\tifffile\tifffile.py", line 1546, in addtag
    ifdvalue = pack(str(count) + dtype, *value)
  File "C:\Python27\lib\site-packages\tifffile\tifffile.py", line 1489, in pack
    return struct.pack(byteorder + fmt, *val)
error: integer out of range for 'I' format code
```

The values I am passing are `resolution=(1577229.798311636, 1580060.0422222703)`

I believe these values worked fine with the current version of tifffile.

**Comment by cgohlke** [comment]
> Can the Python 2.7 version of tifffile store ome metadata?

Initial support for writing OME-TIFF was added in 2020.7.17. The last version to support Python 2.7 was 2019.7.26. 

> Or do I have to fall back to write json in the description?

You could write your own OME-XML to the ImageDescription tag.
