### ISSUE TITLE
accessing Sentinel-1 SLC tiff measurement through S3 procotol

### ISSUE THREAD

**Issue by agrouaze** [cgohlke/tifffile#251]
I want to access Sentinel-1 IW SLC measurement stored in geotiff files.
I tried to reproduced the snippet of #125 :
```python
import fsspec
import tifffile
access_key = 'xxxxxxxxxxxxxxxxxxxxx'
secret_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
entrypoint_url = 'eodata.dataspace.copernicus.eu'
s3 = fsspec.filesystem("s3", anon=False,
   key=access_key,
   secret=secret_key,
   endpoint_url='https://'+entrypoint_url)

s3_flist = [f's3://{f}' for f in s3.ls('/eodata/Sentinel-1/SAR/IW_SLC__1S/2023/02/28/S1A_IW_SLC__1SDV_20230228T041847_20230228T041916_047431_05B1B4_B985.SAFE/measurement/')]
for filename in s3_flist:
    print('filename',filename)
    if '.tiff' in filename and 'iw1' in filename and 'vv' in filename:
        url, name = filename.rsplit('/', 1)
        with tifffile.TiffFile(s3.open(filename), name=name) as tif:
            with tif.series[0].aszarr() as store:
                store.write_fsspec(name + '.json', url=url)
```
But it through this error:
```bash
Traceback (most recent call last):
  File "/home1/datahome/agrouaze/sources/test_tifffile/slicing_lazy_loading_tiffile_s3.py", line 34, in <module>
    store.write_fsspec(name + '.json', url=url)
  File "/opt/conda-envs/dev/lib/python3.10/site-packages/tifffile/tifffile.py", line 12580, in write_fsspec
    raise ValueError(f'{keyframe.sampleformat!r} is' + errormsg)
ValueError: <SAMPLEFORMAT.COMPLEXINT: 5> is not supported by the fsspec ReferenceFileSystem
```
though it is probably an `fsspec` error?

**Comment by cgohlke** [comment]
Complex integers are not supported by fsspec, numpy, zarr, numcodecs, imagecodecs, or zarr. There are [other cases](https://github.com/cgohlke/tifffile/blob/bc49314cfe55d71d72623acaf6aceb3397ffa11a/tifffile/tifffile.py#L12914-L12925) that can not be handled by the fsspec stack.

**Comment by agrouaze** [comment]
> Complex integers are not supported by fsspec, numpy, zarr, numcodecs, or imagecodecs. There are [other cases](https://github.com/cgohlke/tifffile/blob/bc49314cfe55d71d72623acaf6aceb3397ffa11a/tifffile/tifffile.py#L12914-L12925) that can not be handled by the fsspec stack.

Thanks for your answer.
best regards
