### ISSUE TITLE
struct.error: argument out of range

### ISSUE THREAD

**Issue by petsuter** [cgohlke/tifffile#81]
How to reproduce:
```
import tifffile
import numpy
tifffile.imwrite("test.tif", numpy.array([[255]]), resolution=(7411.824413635355, 7411.824413635355))
``` 

(tifffile 2021.4.8)

Error:
```
Traceback (most recent call last):
  File "script.py", line 3, in <module>
    tifffile.imwrite("test.tif", numpy.array([[255]]), resolution=(7411.824413635355, 7411.824413635355))
  File "C:\Python\lib\site-packages\tifffile\tifffile.py", line 866, in imwrite
    result = tif.write(data, shape, dtype, **kwargs)
  File "C:\Python\lib\site-packages\tifffile\tifffile.py", line 2141, in write
    addtag(282, 5, 1, rational(resolution[0]))  # XResolution
  File "C:\Python\lib\site-packages\tifffile\tifffile.py", line 1970, in addtag
    ifdvalue = pack(f'{count}{dataformat}', *value)
  File "C:\Python\lib\site-packages\tifffile\tifffile.py", line 1879, in pack
    return struct.pack(fmt, *val)
struct.error: argument out of range
```

Explanation: [tifffile's rational() function](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L1972) uses `Fraction.from_float().limit_denominator(1000000)`, but the *numerator* is not limited and gets too big for 32bit.

I don't know what the best solution is. I'm considering using this as a workaround:
```
def limit_32bit_numerator(f: float) -> float:
    from fractions import Fraction
    ndigits = 15
    while True:
            r = Fraction.from_float(f).limit_denominator(1000000)
            if r.numerator < 2**32:
                return f
            f = round(f, ndigits)
            ndigits -= 1
```
(Which rounds `7411.824413635355` to `7411.82441363536`. Then `tifffile.imwrite(...)` works fine.)

**Comment by cgohlke** [comment]
Thank you. Will be fixed in the next release.
